// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// EDMeta
Rcpp::List EDMeta(int mcmc_samples, arma::vec beta_hat, arma::vec se, arma::vec min_exposure, arma::vec max_exposure, arma::vec mid_exposure, arma::vec sd_exposure, int exposure_distribution, double metrop_sd_phi_eta_trans, Rcpp::Nullable<int> m_approx, Rcpp::Nullable<int> m_star_approx, Rcpp::Nullable<double> sigma2_mu_prior, Rcpp::Nullable<double> a_tau2_prior, Rcpp::Nullable<double> b_tau2_prior, Rcpp::Nullable<double> a_sigma2_eta_prior, Rcpp::Nullable<double> b_sigma2_eta_prior, Rcpp::Nullable<double> a_phi_eta_prior, Rcpp::Nullable<double> b_phi_eta_prior, Rcpp::Nullable<double> mu_init, Rcpp::Nullable<arma::vec> eta_star_init, Rcpp::Nullable<double> tau2_init, Rcpp::Nullable<double> sigma2_eta_init, Rcpp::Nullable<double> phi_eta_init);
RcppExport SEXP _EDMeta_EDMeta(SEXP mcmc_samplesSEXP, SEXP beta_hatSEXP, SEXP seSEXP, SEXP min_exposureSEXP, SEXP max_exposureSEXP, SEXP mid_exposureSEXP, SEXP sd_exposureSEXP, SEXP exposure_distributionSEXP, SEXP metrop_sd_phi_eta_transSEXP, SEXP m_approxSEXP, SEXP m_star_approxSEXP, SEXP sigma2_mu_priorSEXP, SEXP a_tau2_priorSEXP, SEXP b_tau2_priorSEXP, SEXP a_sigma2_eta_priorSEXP, SEXP b_sigma2_eta_priorSEXP, SEXP a_phi_eta_priorSEXP, SEXP b_phi_eta_priorSEXP, SEXP mu_initSEXP, SEXP eta_star_initSEXP, SEXP tau2_initSEXP, SEXP sigma2_eta_initSEXP, SEXP phi_eta_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type mcmc_samples(mcmc_samplesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_hat(beta_hatSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type se(seSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type min_exposure(min_exposureSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type max_exposure(max_exposureSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mid_exposure(mid_exposureSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sd_exposure(sd_exposureSEXP);
    Rcpp::traits::input_parameter< int >::type exposure_distribution(exposure_distributionSEXP);
    Rcpp::traits::input_parameter< double >::type metrop_sd_phi_eta_trans(metrop_sd_phi_eta_transSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type m_approx(m_approxSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type m_star_approx(m_star_approxSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_mu_prior(sigma2_mu_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_tau2_prior(a_tau2_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_tau2_prior(b_tau2_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_sigma2_eta_prior(a_sigma2_eta_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_sigma2_eta_prior(b_sigma2_eta_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_phi_eta_prior(a_phi_eta_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_phi_eta_prior(b_phi_eta_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type mu_init(mu_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::vec> >::type eta_star_init(eta_star_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type tau2_init(tau2_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_eta_init(sigma2_eta_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type phi_eta_init(phi_eta_initSEXP);
    rcpp_result_gen = Rcpp::wrap(EDMeta(mcmc_samples, beta_hat, se, min_exposure, max_exposure, mid_exposure, sd_exposure, exposure_distribution, metrop_sd_phi_eta_trans, m_approx, m_star_approx, sigma2_mu_prior, a_tau2_prior, b_tau2_prior, a_sigma2_eta_prior, b_sigma2_eta_prior, a_phi_eta_prior, b_phi_eta_prior, mu_init, eta_star_init, tau2_init, sigma2_eta_init, phi_eta_init));
    return rcpp_result_gen;
END_RCPP
}
// beta_true_update
arma::vec beta_true_update(arma::vec beta_hat, arma::mat inv_var_mat, int n, double mu_old, arma::vec eta_star_old, double tau2_old, arma::mat Sigma_eta_star_inv, arma::mat x);
RcppExport SEXP _EDMeta_beta_true_update(SEXP beta_hatSEXP, SEXP inv_var_matSEXP, SEXP nSEXP, SEXP mu_oldSEXP, SEXP eta_star_oldSEXP, SEXP tau2_oldSEXP, SEXP Sigma_eta_star_invSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta_hat(beta_hatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type inv_var_mat(inv_var_matSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type mu_old(mu_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eta_star_old(eta_star_oldSEXP);
    Rcpp::traits::input_parameter< double >::type tau2_old(tau2_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_eta_star_inv(Sigma_eta_star_invSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_true_update(beta_hat, inv_var_mat, n, mu_old, eta_star_old, tau2_old, Sigma_eta_star_inv, x));
    return rcpp_result_gen;
END_RCPP
}
// eta_star_update
arma::vec eta_star_update(arma::vec beta_hat, int m_star, arma::vec beta_true, double mu, double tau2_old, double sigma2_eta_old, arma::mat Sigma_eta_star_inv, arma::mat x);
RcppExport SEXP _EDMeta_eta_star_update(SEXP beta_hatSEXP, SEXP m_starSEXP, SEXP beta_trueSEXP, SEXP muSEXP, SEXP tau2_oldSEXP, SEXP sigma2_eta_oldSEXP, SEXP Sigma_eta_star_invSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta_hat(beta_hatSEXP);
    Rcpp::traits::input_parameter< int >::type m_star(m_starSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_true(beta_trueSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type tau2_old(tau2_oldSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_eta_old(sigma2_eta_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_eta_star_inv(Sigma_eta_star_invSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(eta_star_update(beta_hat, m_star, beta_true, mu, tau2_old, sigma2_eta_old, Sigma_eta_star_inv, x));
    return rcpp_result_gen;
END_RCPP
}
// mu_update
double mu_update(int n, double sigma2_mu_inv, arma::vec beta_true, arma::vec eta_star_old, double tau2_old, arma::mat Sigma_eta_star_inv, arma::mat x);
RcppExport SEXP _EDMeta_mu_update(SEXP nSEXP, SEXP sigma2_mu_invSEXP, SEXP beta_trueSEXP, SEXP eta_star_oldSEXP, SEXP tau2_oldSEXP, SEXP Sigma_eta_star_invSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_mu_inv(sigma2_mu_invSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_true(beta_trueSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eta_star_old(eta_star_oldSEXP);
    Rcpp::traits::input_parameter< double >::type tau2_old(tau2_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_eta_star_inv(Sigma_eta_star_invSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(mu_update(n, sigma2_mu_inv, beta_true, eta_star_old, tau2_old, Sigma_eta_star_inv, x));
    return rcpp_result_gen;
END_RCPP
}
// neg_two_loglike_update
double neg_two_loglike_update(arma::vec beta_hat, arma::vec se, int n, double mu, double tau2, arma::vec eta_star, arma::mat Sigma_eta_star_inv, arma::mat x);
RcppExport SEXP _EDMeta_neg_two_loglike_update(SEXP beta_hatSEXP, SEXP seSEXP, SEXP nSEXP, SEXP muSEXP, SEXP tau2SEXP, SEXP eta_starSEXP, SEXP Sigma_eta_star_invSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta_hat(beta_hatSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type se(seSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eta_star(eta_starSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_eta_star_inv(Sigma_eta_star_invSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(neg_two_loglike_update(beta_hat, se, n, mu, tau2, eta_star, Sigma_eta_star_inv, x));
    return rcpp_result_gen;
END_RCPP
}
// phi_eta_update
Rcpp::List phi_eta_update(int n, int m, arma::vec min_exposure, arma::vec max_exposure, std::vector<arma::mat> abs_d_diffs, arma::mat abs_d_star_diffs, std::vector<arma::mat> exposure_dens, double a_phi_eta, double b_phi_eta, arma::vec beta_true, double mu, double tau2, arma::vec eta_star, double sigma2_eta, double phi_eta_old, arma::mat Sigma_eta_star_inv, arma::mat x, double Sigma_eta_star_inv_log_deter, double metrop_sd_phi_eta_trans, int acctot_phi_eta_trans);
RcppExport SEXP _EDMeta_phi_eta_update(SEXP nSEXP, SEXP mSEXP, SEXP min_exposureSEXP, SEXP max_exposureSEXP, SEXP abs_d_diffsSEXP, SEXP abs_d_star_diffsSEXP, SEXP exposure_densSEXP, SEXP a_phi_etaSEXP, SEXP b_phi_etaSEXP, SEXP beta_trueSEXP, SEXP muSEXP, SEXP tau2SEXP, SEXP eta_starSEXP, SEXP sigma2_etaSEXP, SEXP phi_eta_oldSEXP, SEXP Sigma_eta_star_invSEXP, SEXP xSEXP, SEXP Sigma_eta_star_inv_log_deterSEXP, SEXP metrop_sd_phi_eta_transSEXP, SEXP acctot_phi_eta_transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type min_exposure(min_exposureSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type max_exposure(max_exposureSEXP);
    Rcpp::traits::input_parameter< std::vector<arma::mat> >::type abs_d_diffs(abs_d_diffsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type abs_d_star_diffs(abs_d_star_diffsSEXP);
    Rcpp::traits::input_parameter< std::vector<arma::mat> >::type exposure_dens(exposure_densSEXP);
    Rcpp::traits::input_parameter< double >::type a_phi_eta(a_phi_etaSEXP);
    Rcpp::traits::input_parameter< double >::type b_phi_eta(b_phi_etaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_true(beta_trueSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eta_star(eta_starSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_eta(sigma2_etaSEXP);
    Rcpp::traits::input_parameter< double >::type phi_eta_old(phi_eta_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_eta_star_inv(Sigma_eta_star_invSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type Sigma_eta_star_inv_log_deter(Sigma_eta_star_inv_log_deterSEXP);
    Rcpp::traits::input_parameter< double >::type metrop_sd_phi_eta_trans(metrop_sd_phi_eta_transSEXP);
    Rcpp::traits::input_parameter< int >::type acctot_phi_eta_trans(acctot_phi_eta_transSEXP);
    rcpp_result_gen = Rcpp::wrap(phi_eta_update(n, m, min_exposure, max_exposure, abs_d_diffs, abs_d_star_diffs, exposure_dens, a_phi_eta, b_phi_eta, beta_true, mu, tau2, eta_star, sigma2_eta, phi_eta_old, Sigma_eta_star_inv, x, Sigma_eta_star_inv_log_deter, metrop_sd_phi_eta_trans, acctot_phi_eta_trans));
    return rcpp_result_gen;
END_RCPP
}
// sigma2_eta_update
double sigma2_eta_update(int m_star, double a_sigma2_eta, double b_sigma2_eta, arma::vec eta_star, arma::mat Sigma_eta_star_inv);
RcppExport SEXP _EDMeta_sigma2_eta_update(SEXP m_starSEXP, SEXP a_sigma2_etaSEXP, SEXP b_sigma2_etaSEXP, SEXP eta_starSEXP, SEXP Sigma_eta_star_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type m_star(m_starSEXP);
    Rcpp::traits::input_parameter< double >::type a_sigma2_eta(a_sigma2_etaSEXP);
    Rcpp::traits::input_parameter< double >::type b_sigma2_eta(b_sigma2_etaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eta_star(eta_starSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_eta_star_inv(Sigma_eta_star_invSEXP);
    rcpp_result_gen = Rcpp::wrap(sigma2_eta_update(m_star, a_sigma2_eta, b_sigma2_eta, eta_star, Sigma_eta_star_inv));
    return rcpp_result_gen;
END_RCPP
}
// tau2_update
double tau2_update(int n, double a_tau2, double b_tau2, arma::vec beta_true, double mu, arma::vec eta_star, arma::mat Sigma_eta_star_inv, arma::mat x);
RcppExport SEXP _EDMeta_tau2_update(SEXP nSEXP, SEXP a_tau2SEXP, SEXP b_tau2SEXP, SEXP beta_trueSEXP, SEXP muSEXP, SEXP eta_starSEXP, SEXP Sigma_eta_star_invSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type a_tau2(a_tau2SEXP);
    Rcpp::traits::input_parameter< double >::type b_tau2(b_tau2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_true(beta_trueSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eta_star(eta_starSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_eta_star_inv(Sigma_eta_star_invSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(tau2_update(n, a_tau2, b_tau2, beta_true, mu, eta_star, Sigma_eta_star_inv, x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EDMeta_EDMeta", (DL_FUNC) &_EDMeta_EDMeta, 23},
    {"_EDMeta_beta_true_update", (DL_FUNC) &_EDMeta_beta_true_update, 8},
    {"_EDMeta_eta_star_update", (DL_FUNC) &_EDMeta_eta_star_update, 8},
    {"_EDMeta_mu_update", (DL_FUNC) &_EDMeta_mu_update, 7},
    {"_EDMeta_neg_two_loglike_update", (DL_FUNC) &_EDMeta_neg_two_loglike_update, 8},
    {"_EDMeta_phi_eta_update", (DL_FUNC) &_EDMeta_phi_eta_update, 20},
    {"_EDMeta_sigma2_eta_update", (DL_FUNC) &_EDMeta_sigma2_eta_update, 5},
    {"_EDMeta_tau2_update", (DL_FUNC) &_EDMeta_tau2_update, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_EDMeta(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
