# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EDMeta <- function(mcmc_samples, beta_hat, se, min_exposure, max_exposure, mid_exposure, sd_exposure, exposure_distribution, metrop_sd_phi_eta_trans, m_approx = NULL, m_star_approx = NULL, sigma2_mu_prior = NULL, a_tau2_prior = NULL, b_tau2_prior = NULL, a_sigma2_eta_prior = NULL, b_sigma2_eta_prior = NULL, a_phi_eta_prior = NULL, b_phi_eta_prior = NULL, mu_init = NULL, eta_star_init = NULL, tau2_init = NULL, sigma2_eta_init = NULL, phi_eta_init = NULL) {
    .Call(`_ERMeta_EDMeta`, mcmc_samples, beta_hat, se, min_exposure, max_exposure, mid_exposure, sd_exposure, exposure_distribution, metrop_sd_phi_eta_trans, m_approx, m_star_approx, sigma2_mu_prior, a_tau2_prior, b_tau2_prior, a_sigma2_eta_prior, b_sigma2_eta_prior, a_phi_eta_prior, b_phi_eta_prior, mu_init, eta_star_init, tau2_init, sigma2_eta_init, phi_eta_init)
}

beta_true_update <- function(beta_hat, inv_var_mat, n, mu_old, eta_star_old, tau2_old, Sigma_eta_star_inv, x) {
    .Call(`_ERMeta_beta_true_update`, beta_hat, inv_var_mat, n, mu_old, eta_star_old, tau2_old, Sigma_eta_star_inv, x)
}

eta_star_update <- function(beta_hat, m_star, beta_true, mu, tau2_old, sigma2_eta_old, Sigma_eta_star_inv, x) {
    .Call(`_ERMeta_eta_star_update`, beta_hat, m_star, beta_true, mu, tau2_old, sigma2_eta_old, Sigma_eta_star_inv, x)
}

mu_update <- function(n, sigma2_mu_inv, beta_true, eta_star_old, tau2_old, Sigma_eta_star_inv, x) {
    .Call(`_ERMeta_mu_update`, n, sigma2_mu_inv, beta_true, eta_star_old, tau2_old, Sigma_eta_star_inv, x)
}

neg_two_loglike_update <- function(beta_hat, se, n, mu, tau2, eta_star, Sigma_eta_star_inv, x) {
    .Call(`_ERMeta_neg_two_loglike_update`, beta_hat, se, n, mu, tau2, eta_star, Sigma_eta_star_inv, x)
}

phi_eta_update <- function(n, m, min_exposure, max_exposure, abs_d_diffs, abs_d_star_diffs, exposure_dens, a_phi_eta, b_phi_eta, beta_true, mu, tau2, eta_star, sigma2_eta, phi_eta_old, Sigma_eta_star_inv, x, Sigma_eta_star_inv_log_deter, metrop_sd_phi_eta_trans, acctot_phi_eta_trans) {
    .Call(`_ERMeta_phi_eta_update`, n, m, min_exposure, max_exposure, abs_d_diffs, abs_d_star_diffs, exposure_dens, a_phi_eta, b_phi_eta, beta_true, mu, tau2, eta_star, sigma2_eta, phi_eta_old, Sigma_eta_star_inv, x, Sigma_eta_star_inv_log_deter, metrop_sd_phi_eta_trans, acctot_phi_eta_trans)
}

sigma2_eta_update <- function(m_star, a_sigma2_eta, b_sigma2_eta, eta_star, Sigma_eta_star_inv) {
    .Call(`_ERMeta_sigma2_eta_update`, m_star, a_sigma2_eta, b_sigma2_eta, eta_star, Sigma_eta_star_inv)
}

tau2_update <- function(n, a_tau2, b_tau2, beta_true, mu, eta_star, Sigma_eta_star_inv, x) {
    .Call(`_ERMeta_tau2_update`, n, a_tau2, b_tau2, beta_true, mu, eta_star, Sigma_eta_star_inv, x)
}

